name: voici
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - ipyflex
  - plotly
  - ipywidgets=8.0.6
  - jupyterlab_widgets=3.0.7
  - ipyvuetify
